<?php
$count = $this->grid->getCount();
$pages = (int) ceil($count / $this->itemsPerPage) - 1;

if (!$this->showOnNoPages && $pages <= 0) {
    return;
}

$activePage = $this->getLinkCreator()->getActivePaginationPage();

echo PHP_EOL;
echo str_replace(
    '__ATTRIBUTES__',
    $this->getAttributesString(true),
    $this->holderTagOpen
) . PHP_EOL;

$items = [];
if ($this->firstLabel) {
    $attributes = [];
    if (0 === $activePage) {
        $attributes[] = ' class="active"';
    } else {
        $attributes[] = ' href="' . $this->getLinkCreator()->createPaginationLink(0) . '"';
    }
    
    $items['first'] = str_replace(
        '__ATTRIBUTES__',
        implode(' ', $attributes),
        $this->itemTagOpen
    );
    $items['first'] .= $this->firstLabel;
    $items['first'] .= $this->itemTagClose . PHP_EOL;
}

if ($this->prevLabel) {
    $attributes = [];
    if ($activePage > 0) {
        $attributes[] = ' href="' . $this->getLinkCreator()->createPaginationLink($activePage - 1) . '"';
    }

    $items['prev'] = str_replace(
        '__ATTRIBUTES__',
        implode(' ', $attributes),
        $this->itemTagOpen
    );
    $items['prev'] .= $this->prevLabel;
    $items['prev'] .= $this->itemTagClose . PHP_EOL;
}


for ($i = 0; $i <= $pages; $i++) {

    if ($i < $activePage - $this->itemsBeforeActive
    || $i > $activePage + $this->itemsAfterActive) {
        continue;
    }

    $attributes = [];
    
    if ($i === $activePage) {
        $attributes[] = ' class="active"';
    } else {
        $attributes[] = ' href="' . $this->getLinkCreator()->createPaginationLink($i) . '"';
    }
    $items[$i] = str_replace(
        '__ATTRIBUTES__',
        implode(' ', $attributes),
        $this->itemTagOpen
    );
    $items[$i] .= $i + 1;
    $items[$i] .= $this->itemTagClose . PHP_EOL;
}

if ($this->nextLabel) {
    $attributes = [];
    if ($activePage < $pages) {
        $attributes[] = ' href="' . $this->getLinkCreator()->createPaginationLink($activePage + 1) . '"';
    }
    $items['next'] = str_replace(
        '__ATTRIBUTES__',
        implode(' ', $attributes),
        $this->itemTagOpen
    );
    $items['next'] .= $this->nextLabel;
    $items['next'] .= $this->itemTagClose . PHP_EOL;
}

if ($this->itemTagClose) {
    $attributes = [];
    if ($activePage < $pages) {
        $attributes[] = ' href="' . $this->getLinkCreator()->createPaginationLink($pages) . '"';
    }
    $items['last'] = str_replace(
        '__ATTRIBUTES__',
        implode(' ', $attributes),
        $this->itemTagOpen
    );
    $items['last'] .= $this->lastLabel;
    $items['last'] .= $this->itemTagClose . PHP_EOL;
}


echo implode($this->itemSeparator, $items);

echo $this->holderTagClose . PHP_EOL;
