<?php

echo sprintf(
    '<tr%s>%s',
    $row->getAttributesString(true),
    PHP_EOL
);

$tag = $row->isHead() ? 'th' : 'td';
if ($row->isString()) {
    $row->setAttribute('colspan', count($this->grid->getColumns()));
    echo sprintf(
            '<%s%s>%s</%s>%s',
            $tag,
            $row->getAttributesString(true),
            (string) $row->getSource(),
            $tag,
            PHP_EOL
      );
} else {
    foreach ($this->grid->getColumns() as $column) {
        echo sprintf(
            '<%s%s>%s</%s>%s',
            $tag,
            $row->getAttributesString(true),
            $row[$column->getName()],
            $tag,
            PHP_EOL
        );
    }
}

echo '</tr>' . PHP_EOL;
