<?php

echo sprintf(
    '<tr%s>%s',
    $row->getAttributesString(true),
    PHP_EOL
);

$tag = $row instanceof Grid\Row\HeadRow? 'th' : 'td';
if ($row->isString()) {
    echo sprintf(
            '<td colspan="%s">%s</td>%s',
            count($this->grid->getColumns()),
            (string) $row->getSource(),
            PHP_EOL
      );
} else {
    foreach ($this->grid->getColumns() as $column) {
        echo sprintf(
            '<%s>%s</%s>%s',
            $tag,
            $row[$column->getName()],
            $tag,
            PHP_EOL
        );
    }
}

echo '</tr>' . PHP_EOL;
